name: edulingokids
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_fireworks: ^1.0.8
  confetti: ^0.8.0
  lottie: ^3.3.1
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3  # << Moved here if you only use it for dev

flutter:
  uses-material-design: true
  assets:
    - assets/icons/1.png
    - assets/icons/2.png
    - assets/sounds/correct.wav
    - assets/sounds/false.wav

flutter_icons:  # <<<<< This should be here, outside 'flutter'
  android: true
  ios: true
  image_path: "assets/logo.png"
